const info = `
SERVER_PORT=8000
DATABASE_PORT=3306
DATABASE_NAME=blogger
DATABASE_HOST=localhost
DATABASE_USER=root
DATABASE_PASSWORD=
DATABASE_TABLE_NAME=users
DB_URI=mysql://root@localhost:3306/blogger
JWT_SECRET_TOKEN=khondokhondocetonagulochetonahinhoyeroysarthohasilermohautsobesottorakorevoy
JWT_SECRET_TOKEN_EXPIRE_TIME=86400
JWT_SECRET_TOKEN_ALGORITHM=HS256


`