const info = `
SERVER_PORT=7000
DATABASE_PORT=3306
DATABASE_NAME=database
DATABASE_HOST=localhost
DATABASE_USER=root
DATABASE_PASSWORD=
DATABASE_TABLE_NAME=table
DB_URI=mysql://root@localhost:3306/database
JWT_SECRET_TOKEN=abcdefghij
JWT_SECRET_TOKEN_EXPIRE_TIME=20min
JWT_SECRET_TOKEN_ALGORITHM=HS256

`